############## springbootdemo配置 ##############
springbootdemo:
  swagger-open: true
  kaptcha-open: false
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  # file-upload-path: e:/tmp #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validate-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

############## 项目启动端口 ##############
server:
  port: 8080

############## beetl配置 ##############
beetl:
  delimiter-statement-start: \@ #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags #自定义标签文件ROOT目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: trur #是否检测文件变化，开发用ttrue，但线上用false

############## spring 配置 ##############
spring:
  redis:
    host: localhost
    port: 6379
    password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-request-size: 100MB #最大的请求大小
      max-file-size: 100MB #最大的文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具
      additional-paths: src/main/java
      exclude: static/**, WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认的动态代理，true启用cglib的动态代理

############## mybasti-plus 配置 ##############
mybatis-plus:
  mapper-locations: classpath*:com/springboot/**/mapper/*.xml
  typeAliasesPackage: com.springboot.common.persistence.model
  typeEnumsPackage: com.springboot.common.constant.enums
  global-config:
    id-type: 0 #0:数据库Id自增 1:用户输入id 2:全局唯一id(IdWorker) 3:全局唯一ID(uuid)
    db-column-underline: false #全局表为下划线命名设置 true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置缓存的全局开关
    lazyLoadingEnabled: true  #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql:127.0.0.1:3306/springbootdemodb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    db-name: springbootdemodb
    filters: log4j,wall,mergeStat

#flowable数据源和多数据源配置
springbootdemo:
  flowable:
    datasource:
      url: jdbc:mysql:127.0.0.1:3306/springbootdemodb_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
  muti-datasource:
    default-datasource-name: dataSourceSpringbootdemo #默认数据源的名称
    url: jdbc:mysql:127.0.0.1:3306/springbootdemodb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root

logging:
  level.root: info
  level.com.springboot: debug
  path: logs/
  file: springbootdemo.log


##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    url: jdbc:mysql:127.0.0.1:3306/springbootdemodb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs/
  file: springbootdemo.log
